"""ISO 4217 currency seed data.

Mirrors the reference Laravel `CurrenciesTableSeeder` (72 rows) and
extends it with additional ISO 4217 entries so we seed 150+ currencies
as required by the Sprint 2 acceptance criteria.
"""

CURRENCIES: list[dict] = [
    {"name": 'US Dollar', "code": 'USD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'British Pound', "code": 'GBP', "symbol": '£', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Euro', "code": 'EUR', "symbol": '€', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'South African Rand', "code": 'ZAR', "symbol": 'R', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Danish Krone', "code": 'DKK', "symbol": 'kr', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Israeli Shekel', "code": 'ILS', "symbol": 'NIS ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Swedish Krona', "code": 'SEK', "symbol": 'kr', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Kenyan Shilling', "code": 'KES', "symbol": 'KSh ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Kuwaiti Dinar', "code": 'KWD', "symbol": 'KWD ', "precision": 3, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Canadian Dollar', "code": 'CAD', "symbol": 'C$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Philippine Peso', "code": 'PHP', "symbol": 'P ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Nepali Rupee', "code": 'NPR', "symbol": 'रू', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Indian Rupee', "code": 'INR', "symbol": '₹', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Australian Dollar', "code": 'AUD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Singapore Dollar', "code": 'SGD', "symbol": 'S$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Norske Kroner', "code": 'NOK', "symbol": 'kr', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'New Zealand Dollar', "code": 'NZD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Vietnamese Dong', "code": 'VND', "symbol": '₫', "precision": 0, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Swiss Franc', "code": 'CHF', "symbol": 'Fr.', "precision": 2, "thousand_separator": '\\', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Guatemalan Quetzal', "code": 'GTQ', "symbol": 'Q', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Malaysian Ringgit', "code": 'MYR', "symbol": 'RM', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Brazilian Real', "code": 'BRL', "symbol": 'R$', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Thai Baht', "code": 'THB', "symbol": '฿', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Nigerian Naira', "code": 'NGN', "symbol": '₦', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Argentine Peso', "code": 'ARS', "symbol": '$', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Bangladeshi Taka', "code": 'BDT', "symbol": 'Tk', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'United Arab Emirates Dirham', "code": 'AED', "symbol": 'DH ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Hong Kong Dollar', "code": 'HKD', "symbol": 'HK$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Indonesian Rupiah', "code": 'IDR', "symbol": 'Rp', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Mexican Peso', "code": 'MXN', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Egyptian Pound', "code": 'EGP', "symbol": 'E£', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Colombian Peso', "code": 'COP', "symbol": '$', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Central African Franc', "code": 'XAF', "symbol": 'CFA ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'West African Franc', "code": 'XOF', "symbol": 'CFA ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Chinese Renminbi', "code": 'CNY', "symbol": 'RMB ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Rwandan Franc', "code": 'RWF', "symbol": 'RF ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Tanzanian Shilling', "code": 'TZS', "symbol": 'TSh ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Netherlands Antillean Guilder', "code": 'ANG', "symbol": 'NAƒ', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Trinidad and Tobago Dollar', "code": 'TTD', "symbol": 'TT$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'East Caribbean Dollar', "code": 'XCD', "symbol": 'EC$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Ghanaian Cedi', "code": 'GHS', "symbol": '\u200eGH₵', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bulgarian Lev', "code": 'BGN', "symbol": 'Лв.', "precision": 2, "thousand_separator": ' ', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Aruban Florin', "code": 'AWG', "symbol": 'Afl. ', "precision": 2, "thousand_separator": ' ', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Turkish Lira', "code": 'TRY', "symbol": 'TL ', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Romanian New Leu', "code": 'RON', "symbol": 'RON', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Croatian Kuna', "code": 'HRK', "symbol": 'kn', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Saudi Riyal', "code": 'SAR', "symbol": '\u200eSِAR', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Japanese Yen', "code": 'JPY', "symbol": '¥', "precision": 0, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Maldivian Rufiyaa', "code": 'MVR', "symbol": 'Rf', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Costa Rican Colón', "code": 'CRC', "symbol": '₡', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Pakistani Rupee', "code": 'PKR', "symbol": 'Rs ', "precision": 0, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Polish Zloty', "code": 'PLN', "symbol": 'zł', "precision": 2, "thousand_separator": ' ', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Sri Lankan Rupee', "code": 'LKR', "symbol": 'LKR', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": True},
    {"name": 'Czech Koruna', "code": 'CZK', "symbol": 'Kč', "precision": 2, "thousand_separator": ' ', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Uruguayan Peso', "code": 'UYU', "symbol": '$', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Namibian Dollar', "code": 'NAD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Tunisian Dinar', "code": 'TND', "symbol": '\u200eد.ت', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Russian Ruble', "code": 'RUB', "symbol": '₽', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Mozambican Metical', "code": 'MZN', "symbol": 'MT', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Omani Rial', "code": 'OMR', "symbol": 'ر.ع.', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Ukrainian Hryvnia', "code": 'UAH', "symbol": '₴', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Macanese Pataca', "code": 'MOP', "symbol": 'MOP$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Taiwan New Dollar', "code": 'TWD', "symbol": 'NT$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Dominican Peso', "code": 'DOP', "symbol": 'RD$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Chilean Peso', "code": 'CLP', "symbol": '$', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Serbian Dinar', "code": 'RSD', "symbol": 'RSD', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Kyrgyzstani som', "code": 'KGS', "symbol": 'С̲ ', "precision": 2, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": False},
    {"name": 'Iraqi Dinar', "code": 'IQD', "symbol": 'ع.د', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Peruvian Soles', "code": 'PEN', "symbol": 'S/', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Moroccan Dirham', "code": 'MAD', "symbol": 'DH', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Jamaican Dollar', "code": 'JMD', "symbol": '$', "precision": 0, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Macedonian Denar', "code": 'MKD', "symbol": 'ден', "precision": 0, "thousand_separator": '.', "decimal_separator": ',', "swap_currency_symbol": True},
    {"name": 'Albanian Lek', "code": 'ALL', "symbol": 'L', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Algerian Dinar', "code": 'DZD', "symbol": 'د.ج', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Angolan Kwanza', "code": 'AOA', "symbol": 'Kz', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Armenian Dram', "code": 'AMD', "symbol": '֏', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Azerbaijani Manat', "code": 'AZN', "symbol": '₼', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bahamian Dollar', "code": 'BSD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bahraini Dinar', "code": 'BHD', "symbol": '.د.ب', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Barbadian Dollar', "code": 'BBD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Belarusian Ruble', "code": 'BYN', "symbol": 'Br', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Belize Dollar', "code": 'BZD', "symbol": 'BZ$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bermudian Dollar', "code": 'BMD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bhutanese Ngultrum', "code": 'BTN', "symbol": 'Nu.', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bolivian Boliviano', "code": 'BOB', "symbol": 'Bs.', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Bosnia-Herzegovina Convertible Mark', "code": 'BAM', "symbol": 'KM', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Botswanan Pula', "code": 'BWP', "symbol": 'P', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Brunei Dollar', "code": 'BND', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Burundian Franc', "code": 'BIF', "symbol": 'Fr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Cambodian Riel', "code": 'KHR', "symbol": '៛', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Cape Verdean Escudo', "code": 'CVE', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Cayman Islands Dollar', "code": 'KYD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Chilean Unit of Account (UF)', "code": 'CLF', "symbol": 'UF', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Comorian Franc', "code": 'KMF', "symbol": 'Fr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Congolese Franc', "code": 'CDF', "symbol": 'Fr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Cuban Convertible Peso', "code": 'CUC', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Cuban Peso', "code": 'CUP', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Djiboutian Franc', "code": 'DJF', "symbol": 'Fr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Eritrean Nakfa', "code": 'ERN', "symbol": 'Nfk', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Ethiopian Birr', "code": 'ETB', "symbol": 'Br', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Falkland Islands Pound', "code": 'FKP', "symbol": '£', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Fijian Dollar', "code": 'FJD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Gambian Dalasi', "code": 'GMD', "symbol": 'D', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Georgian Lari', "code": 'GEL', "symbol": '₾', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Gibraltar Pound', "code": 'GIP', "symbol": '£', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Guinean Franc', "code": 'GNF', "symbol": 'Fr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Guyanaese Dollar', "code": 'GYD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Haitian Gourde', "code": 'HTG', "symbol": 'G', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Honduran Lempira', "code": 'HNL', "symbol": 'L', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Hungarian Forint', "code": 'HUF', "symbol": 'Ft', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Icelandic Krona', "code": 'ISK', "symbol": 'kr', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Iranian Rial', "code": 'IRR', "symbol": '﷼', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Jordanian Dinar', "code": 'JOD', "symbol": 'د.ا', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Kazakhstani Tenge', "code": 'KZT', "symbol": '₸', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Korean Won', "code": 'KRW', "symbol": '₩', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Laotian Kip', "code": 'LAK', "symbol": '₭', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Lebanese Pound', "code": 'LBP', "symbol": 'ل.ل', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Lesotho Loti', "code": 'LSL', "symbol": 'L', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Liberian Dollar', "code": 'LRD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Libyan Dinar', "code": 'LYD', "symbol": 'ل.د', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Malagasy Ariary', "code": 'MGA', "symbol": 'Ar', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Malawian Kwacha', "code": 'MWK', "symbol": 'MK', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Mauritanian Ouguiya', "code": 'MRU', "symbol": 'UM', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Mauritian Rupee', "code": 'MUR', "symbol": '₨', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Moldovan Leu', "code": 'MDL', "symbol": 'L', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Mongolian Tugrik', "code": 'MNT', "symbol": '₮', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Myanma Kyat', "code": 'MMK', "symbol": 'K', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Nicaraguan Cordoba', "code": 'NIO', "symbol": 'C$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'North Korean Won', "code": 'KPW', "symbol": '₩', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Panamanian Balboa', "code": 'PAB', "symbol": 'B/.', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Papua New Guinean Kina', "code": 'PGK', "symbol": 'K', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Paraguayan Guarani', "code": 'PYG', "symbol": '₲', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Qatari Rial', "code": 'QAR', "symbol": 'ر.ق', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Samoan Tala', "code": 'WST', "symbol": 'T', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Sao Tome and Principe Dobra', "code": 'STN', "symbol": 'Db', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Seychellois Rupee', "code": 'SCR', "symbol": '₨', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Sierra Leonean Leone', "code": 'SLL', "symbol": 'Le', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Solomon Islands Dollar', "code": 'SBD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Somali Shilling', "code": 'SOS', "symbol": 'Sh', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Sudanese Pound', "code": 'SDG', "symbol": 'ج.س.', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Surinamese Dollar', "code": 'SRD', "symbol": '$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Swazi Lilangeni', "code": 'SZL', "symbol": 'L', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Syrian Pound', "code": 'SYP', "symbol": '£', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Tajikistani Somoni', "code": 'TJS', "symbol": 'ЅМ', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": "Tongan Pa'anga", "code": 'TOP', "symbol": 'T$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Turkmenistani Manat', "code": 'TMT', "symbol": 'm', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Ugandan Shilling', "code": 'UGX', "symbol": 'Sh', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Uzbekistani Som', "code": 'UZS', "symbol": "so'm", "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Vanuatu Vatu', "code": 'VUV', "symbol": 'Vt', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Venezuelan Bolivar Soberano', "code": 'VES', "symbol": 'Bs.S', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Yemeni Rial', "code": 'YER', "symbol": '﷼', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Zambian Kwacha', "code": 'ZMW', "symbol": 'ZK', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
    {"name": 'Zimbabwean Dollar', "code": 'ZWL', "symbol": 'Z$', "precision": 2, "thousand_separator": ',', "decimal_separator": '.', "swap_currency_symbol": False},
]
